Added a test for ensuring no other modules.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -40,11 +40,23 @@ test:
       set -x # Test the drupals
       docker-compose exec -T cli drush status
     - |
-      set -x # Can't update modules.
+      set -x # Can't update existing module.
       set +e
       ERR=1 && composer require drupal/redirect 1.x-dev || ERR=$?
       set -e
-      if [ "$ERR" -eq 0 ]; then echo "Should fail to install." && exit 1; fi
+      if [ "$ERR" -eq 0 ]; then echo "Correctly fails to install dev version redirect." && exit 1; fi
+    - |
+      set -x # Can't update undesireable version.
+      set +e
+      ERR=1 && composer require drupal/bad_judgement || ERR=$?
+      set -e
+      if [ "$ERR" -eq 0 ]; then echo "Correctly fails add bad judgement." && exit 1; fi
+    - |
+      set -x # Can't add undesired module.
+      set +e
+      ERR=1 && composer require drupal/bad_judgement || ERR=$?
+      set -e
+      if [ "$ERR" -eq 0 ]; then echo "Correctly fails add bad judgement." && exit 1; fi
 
 before_script:
   - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
